/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ShortpinkImage from 'src/assets/images/guestpartyroom_shortpink.png';
import Chair1Image from 'src/assets/images/guestpartyroom_chair.png';
import Chair2Image from 'src/assets/images/guestpartyroom_chair_1.png';
import Chair3Image from 'src/assets/images/guestpartyroom_chair_2.png';
import Chair4Image from 'src/assets/images/guestpartyroom_chair_3.png';
import Chair5Image from 'src/assets/images/guestpartyroom_chair_4.png';
import Chair6Image from 'src/assets/images/guestpartyroom_chair_5.png';
import Chair7Image from 'src/assets/images/guestpartyroom_chair_6.png';
import Chair8Image from 'src/assets/images/guestpartyroom_chair_7.png';
import Chair9Image from 'src/assets/images/guestpartyroom_chair_8.png';
import Chair10Image from 'src/assets/images/guestpartyroom_chair_9.png';
import Chair11Image from 'src/assets/images/guestpartyroom_chair_10.png';
import Q3Image from 'src/assets/images/guestpartyroom_____.png';
import TableImage from 'src/assets/images/table.png';
import { styled } from '@mui/material/styles';
import { Link } from 'react-router-dom';

const GuestPartyroom1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Q = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `120.01px`,
  height: `54.55px`,
  left: `137px`,
  top: `778px`,
});

const Shortpink = styled('img')({
  height: `54.55px`,
  width: `120.01px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `37px`,
  top: `12px`,
});

const Q2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `154px`,
  height: `45px`,
  position: `absolute`,
  left: `118px`,
  top: `27px`,
});

const Chair = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `331px`,
  height: `528.17px`,
  left: `32px`,
  top: `130px`,
});

const Chair1 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `140px`,
  top: `0px`,
});

const Chair2 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `94px`,
});

const Chair3 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `474px`,
});

const Chair4 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `94px`,
});

const Chair5 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `189px`,
});

const Chair6 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `284px`,
});

const Chair7 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `379px`,
});

const Chair8 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `474px`,
});

const Chair9 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `189px`,
});

const Chair10 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `284px`,
});

const Chair11 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `379px`,
});

const Q3 = styled('img')({
  height: `125.9px`,
  width: `120px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `137px`,
  top: `67px`,
});

const Table = styled('img')({
  height: `600px`,
  width: `193.55px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `100px`,
  top: `163px`,
});

function GuestPartyroom(props) {
  return (
    <GuestPartyroom1 className={props.className}>
      <Link to="/Home">
        <Q>
          <Shortpink src={ShortpinkImage} loading="lazy" alt={'shortpink'} />
          <Q1>{`종료`}</Q1>
        </Q>
      </Link>
      <Q2>{`현재 파티장 모습`}</Q2>
      <Chair>
        <Chair1 src={Chair1Image} loading="lazy" alt={'chair'} />
        <Chair2 src={Chair2Image} loading="lazy" alt={'chair'} />
        <Chair3 src={Chair3Image} loading="lazy" alt={'chair'} />
        <Chair4 src={Chair4Image} loading="lazy" alt={'chair'} />
        <Chair5 src={Chair5Image} loading="lazy" alt={'chair'} />
        <Chair6 src={Chair6Image} loading="lazy" alt={'chair'} />
        <Chair7 src={Chair7Image} loading="lazy" alt={'chair'} />
        <Chair8 src={Chair8Image} loading="lazy" alt={'chair'} />
        <Chair9 src={Chair9Image} loading="lazy" alt={'chair'} />
        <Chair10 src={Chair10Image} loading="lazy" alt={'chair'} />
        <Chair11 src={Chair11Image} loading="lazy" alt={'chair'} />
      </Chair>
      <Q3 src={Q3Image} loading="lazy" alt={'고라니'} />
      <Table src={TableImage} loading="lazy" alt={'table'} />
    </GuestPartyroom1>
  );
}

export default GuestPartyroom;
