/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ButtonPinkImage from 'src/assets/images/guestletterdone_button_pink.png';
import EnvelopeImage from 'src/assets/images/guestenvelope.png';
import { styled } from '@mui/material/styles';
import { Link } from "react-router-dom";

const GuestLetterDone1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle10 = styled('div')({
  backgroundColor: `rgba(246, 232, 228, 1)`,
  borderRadius: `40px`,
  width: `354px`,
  height: `731px`,
  position: `absolute`,
  left: `18px`,
  top: `43px`,
});

const Group5 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `54.55px`,
  left: `75px`,
  top: `666px`,
});

const ButtonPink = styled('img')({
  height: `54.55px`,
  width: `240px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `60px`,
  top: `12px`,
});

const Q1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `295px`,
  height: `59px`,
  position: `absolute`,
  left: `47px`,
  top: `463px`,
});

const Envelope = styled('img')({
  height: `144.44px`,
  width: `200px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `95px`,
  top: `246px`,
});

function GuestLetterDone(props) {
  return (
    <GuestLetterDone1 className={props.className}>
      <Rectangle10></Rectangle10>
      <Link to="/GuestPartyroom">
        <Group5>
          <ButtonPink src={ButtonPinkImage} loading="lazy" alt={'button_pink'} />
          <Q>{`파티장 가기`}</Q>
        </Group5>
      </Link>
      <Q1>
        {`케이크 한 층과 함께
편지가 안전하게 전달되었습니다.`}
      </Q1>
      <Envelope src={EnvelopeImage} loading="lazy" alt={'envelope'} />
    </GuestLetterDone1>
  );
}

export default GuestLetterDone;
