/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import LongletterImage from 'src/assets/images/guestletter_longletter.png';
import ButtonPinkImage from 'src/assets/images/guestletter_button_pink.png';
import Q11Image from 'src/assets/images/guestletter___________1.png';
import { styled } from '@mui/material/styles';
import { Link } from "react-router-dom";

const GuestLetter1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Longletter = styled('img')({
  height: `730px`,
  width: `324.44px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `33px`,
  top: `24px`,
});

const Group11 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `159px`,
  height: `135px`,
  left: `158px`,
  top: `91px`,
});

const Q = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `135px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(188, 137, 141, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `70px`,
  top: `219px`,
});

const Q050 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(188, 137, 141, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `274px`,
  top: `674px`,
});

const Group10 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `46px`,
  height: `58px`,
  left: `166px`,
  top: `83px`,
});

const Q2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(188, 137, 141, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `54.55px`,
  left: `77px`,
  top: `771px`,
});

const ButtonPink = styled('img')({
  height: `54.55px`,
  width: `240px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q4 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `58px`,
  top: `12px`,
});

const Q11 = styled('img')({
  height: `122px`,
  width: `115px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `43px`,
  top: `80px`,
});

const Rectangle11 = styled('div')({
  backgroundColor: `rgba(246, 232, 228, 1)`,
  borderRadius: `40px`,
  width: `260px`,
  height: `415px`,
  position: `absolute`,
  left: `65px`,
  top: `272px`,
});

const Q47Hgxwch1930 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `215px`,
  height: `343px`,
  position: `absolute`,
  left: `91px`,
  top: `307px`,
});

function GuestLetter(props) {
  return (
    <GuestLetter1 className={props.className}>
      <Longletter src={LongletterImage} loading="lazy" alt={'longletter'} />
      <Group11>
        <Q>{`______ 에게 편지를 작성합니다!`}</Q>
      </Group11>
      <Q1>{`친구에게 축하 메세지 작성하기`}</Q1>
      <Q050>{`0/50`}</Q050>
      <Group10>
        <Q2>{`닉네임`}</Q2>
      </Group10>
      <Link to="/GuestLetterDone">
        <Q3>
          <ButtonPink src={ButtonPinkImage} loading="lazy" alt={'button_pink'} />
          <Q4>{`편지 보내기`}</Q4>
        </Q3>
      </Link>
      <Q11 src={Q11Image} loading="lazy" alt={'새싹냥 1'} />
      <Rectangle11></Rectangle11>
      <Q47Hgxwch1930>
        {`이 편지는 영국에서 최초로 시작되어 일년에 한 바퀴 돌면서 받는 사람에게
행운을 주었고 지금은 당신에게로 옮겨진 이 편지는 4일 안에 당신 곁을 떠나야 합니다.
이 편지를 포함해서 7통을 행운이 필요한 사람에게 보내 주셔야 합니다.
복사를 해도 좋습니다. 혹 미신이라 하실지 모르지만 사실입니다.
영국에서 HGXWCH이라는 사람은 1930년에 이 편지를 받았습니다. 그는 비서에`}
      </Q47Hgxwch1930>
    </GuestLetter1>
  );
}

export default GuestLetter;
